# Functioncode   COIL   0x01

external_components:
  - source: github://creepystefan/esphome_tcp


sensor:
  - platform: dimplex
    name: a-voltage
    host: 192.168.178.46
    functioncode: 4
    register_address: 1021
  
  - platform: dimplex
    name: b-voltage
    host: 192.168.178.46
    functioncode: 4
    register_address: 1041
  
