external_components:
  - source: github://creepystefan/esphome_tcp
    refresh: 0s

sensor:
  - platform: dimplex
    name: a-voltage
    host: 192.168.178.46
    port: 502
    functioncode: 4
    register_address: 1021
  
  - platform: dimplex
    name: b-voltage
    host: 192.168.178.46
    functioncode: 4
    register_address: 1041
  
