####  NOT FINISHED #####
#### Port is Optional ( Standard 502 )

modbustcp:
  id: modbus1
  ip_address: 192.168.178.46
  port: 501
  unit_id: 3
  

sensor:
  - platform: modbustcpsensor
    name: A
    functioncode: 4
    address: 11
  - platform: modbustcpsensor
    name: A
    functioncode: 3
    address: 9
