external_components:
  - source: github://creepystefan/esphome_tcp
    refresh: 0s

        # full config with Options
sensor:
  - platform: modbus_tcp_16
    name: NAME
    host: 192.168.178.46
    port: 502
    functioncode: 4
    register_address: 1

    
        # only required
  - platform: modbus_tcp_16
    name: NAME
    host: 192.168.178.46
    functioncode: 4
    register_address: 1
